name: CI for tqsdk-python-private

on:
  push:

jobs:
  setup:
    name: log the workflow url in src repo in pr comment
    runs-on: ubuntu-20.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Add comment show workflow url
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GH_PAT }}
          repository: shinnytech/tqsdk-python-private
          issue-number: "715"
          comment-id: "2602534734"
          body: |
            - Workflow url: https://github.com/shinnytech/tqsdk-ci/actions/runs/${{ github.run_id }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: shinnytech/tqsdk-python-private
          ref: "chenli/profile_memory_during_ci"
          token: ${{ secrets.GH_PAT }}

      - name: Giant Files List
        id: giant-files-list
        run: |
          git ls-files | xargs ls -l | sort -nrk5 | awk '{if($5 > ${{ secrets.FILE_LIMIT_SIZE }}) print $9 }' | xargs ls -lrth
          echo "::set-output name=GIANT-FILES-COUNT::$(git ls-files | xargs ls -l | sort -nrk5 | awk '{if($5 > ${{ secrets.FILE_LIMIT_SIZE }}) print $0}' | wc -l)"

      - name: Giant Files Check
        if: steps.giant-files-list.outputs.GIANT-FILES-COUNT != 0
        run: |
          echo "files size check failed"
          exit 1

  build-web:
    name: build web packages
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: shinnytech/tqsdk-python-private
          ref: "chenli/profile_memory_during_ci"
          token: ${{ secrets.GH_PAT }}
          submodules: 'recursive'

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Package web
        run: |
          cd ./web/
          yarn config set "strict-ssl" false -g
          yarn install --frozen-lockfile
          yarn run build
        env:
          CI: true

      - name: Upload web package
        uses: actions/upload-artifact@v4
        with:
          name: web-files
          path: tqsdk/web/*

  test-and-build:
    needs: build-web
    strategy:
      matrix:
        envinfo:
          - { name: 'linux-3.7-x64', os: ubuntu-20.04, python-version: 3.7.x, python-arch: x64, TZ: 'Asia/Shanghai', bdist-platform: 'manylinux1_x86_64' }
          - { name: 'linux-3.8-x64', os: ubuntu-20.04, python-version: 3.8.x, python-arch: x64, TZ: 'Asia/Shanghai', bdist-platform: 'manylinux1_x86_64' }
          - { name: 'linux-3.9-x64', os: ubuntu-20.04, python-version: 3.9.x, python-arch: x64, TZ: 'Asia/Shanghai', bdist-platform: 'manylinux1_x86_64' }
          - { name: 'linux-3.9-x64', os: ubuntu-20.04, python-version: 3.9.x, python-arch: x64, TZ: '', bdist-platform: 'manylinux1_x86_64' }
          - { name: 'linux-3.10-x64', os: ubuntu-20.04, python-version: 3.10.x, python-arch: x64, TZ: 'Asia/Shanghai', bdist-platform: 'manylinux1_x86_64' }
          #          - { name: 'linux-3.11-x64', os: ubuntu-20.04, python-version: 3.11.x, python-arch: x64, TZ: 'Asia/Shanghai', bdist-platform: 'manylinux1_x86_64'}
          #          - { name: 'linux-3.12-x64', os: ubuntu-20.04, python-version: 3.12.x, python-arch: x64, TZ: 'Asia/Shanghai', bdist-platform: 'manylinux1_x86_64'}
          - { name: 'macos-3.7-x64', os: macos-13, python-version: 3.7.x, python-arch: x64, TZ: 'Asia/Shanghai', bdist-platform: 'any' }
          - { name: 'macos-3.8-x64', os: macos-13, python-version: 3.8.x, python-arch: x64, TZ: 'Asia/Shanghai', bdist-platform: 'any' }
          - { name: 'macos-3.9-x64', os: macos-13, python-version: 3.9.x, python-arch: x64, TZ: 'Asia/Shanghai', bdist-platform: 'any' }
          - { name: 'macos-3.10-x64', os: macos-13, python-version: 3.10.x, python-arch: x64, TZ: 'Asia/Shanghai', bdist-platform: 'any' }
          #          - { name: 'macos-3.11-x64', os: macos-latest, python-version: 3.11.x, python-arch: x64, TZ: 'Asia/Shanghai', bdist-platform: 'any'}
          #          - { name: 'macos-3.12-x64', os: macos-latest, python-version: 3.12.x, python-arch: x64, TZ: 'Asia/Shanghai', bdist-platform: 'any'}
          - { name: 'windows-3.7-x64', os: windows-latest, python-version: 3.7.x, python-arch: x64, TZ: 'CST-8', bdist-platform: 'win_amd64' }
          - { name: 'windows-3.7-x86', os: windows-latest, python-version: 3.7.x, python-arch: x86, TZ: 'CST-8', bdist-platform: 'win32' }
          - { name: 'windows-3.8-x64', os: windows-latest, python-version: 3.8.x, python-arch: x64, TZ: 'CST-8', bdist-platform: 'win_amd64' }
          - { name: 'windows-3.8-x86', os: windows-latest, python-version: 3.8.x, python-arch: x86, TZ: 'CST-8', bdist-platform: 'win32' }
          - { name: 'windows-3.9-x64', os: windows-latest, python-version: 3.9.x, python-arch: x64, TZ: 'CST-8', bdist-platform: 'win_amd64' }
          - { name: 'windows-3.9-x86', os: windows-latest, python-version: 3.9.x, python-arch: x86, TZ: 'CST-8', bdist-platform: 'win32' }
          - { name: 'windows-3.10-x64', os: windows-latest, python-version: 3.10.x, python-arch: x64, TZ: 'CST-8', bdist-platform: 'win_amd64' }
    #          - { name: 'windows-3.10-x86', os: windows-latest, python-version: 3.10.x, python-arch: x86, TZ: 'CST-8', bdist-platform: 'win32'}
    #          - { name: 'windows-3.11-x64', os: windows-latest, python-version: 3.11.x, python-arch: x64, TZ: 'CST-8', bdist-platform: 'win_amd64'}
    #          - { name: 'windows-3.11-x86', os: windows-latest, python-version: 3.11.x, python-arch: x86, TZ: 'CST-8', bdist-platform: 'win32'}
    #          - { name: 'windows-3.12-x64', os: windows-latest, python-version: 3.12.x, python-arch: x64, TZ: 'CST-8', bdist-platform: 'win_amd64'}
    #          - { name: 'windows-3.12-x86', os: windows-latest, python-version: 3.12.x, python-arch: x86, TZ: 'CST-8', bdist-platform: 'win32'}
    # py11 py12 默认的 hash 算法改变，导致测试脚本需要变更，暂时不加在 ci 中，后续计划只在 py11 py12 上运行 ci，需要重新录制脚本


    env:
      PYTHONUNBUFFERED: 1
      PYTHONIOENCODING: "utf-8"
      PYTHONHASHSEED: 32
      TZ: ${{ matrix.envinfo.TZ }}
      TESTLOGPATH: "./log_archive/"
      TESTLOGNAME: ${{ matrix.envinfo.name }}
      TQSDK_RUN_TEST: true

    runs-on: ${{ matrix.envinfo.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: shinnytech/tqsdk-python-private
          ref: "chenli/profile_memory_during_ci"
          token: ${{ secrets.GH_PAT }}

      - name: Download web-files
        uses: actions/download-artifact@v4
        with:
          name: web-files
          path: ./tqsdk/web

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.envinfo.python-version}}
          architecture: ${{matrix.envinfo.python-arch}}

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ matrix.envinfo.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ matrix.envinfo.os }}-pip-

      - name: Install dependencies setuptools
        if: matrix.envinfo.python-version == '3.7.x' || matrix.envinfo.python-version == '3.8.x' || matrix.envinfo.python-version == '3.9.x'
        run: |
          python -m pip install setuptools==59.6.0

      - name: Install dependencies
        run: |
          python -c "import platform;import sys;print(sys.platform, platform.python_version(), platform.system(), platform.machine());"
          git lfs install
          git lfs pull
          python -m pip install wheel==0.34.2
          python -m pip install setuptools
          python -m pip install Sphinx==3.3.1

      # pandas 在 py>=3.8 时需要安装 pyarrow, 否则报错 DeprecationWarning：Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
      - name: Install dependencies pyarrow
        if: matrix.envinfo.bdist-platform != 'win32' && matrix.envinfo.python-version != '3.7.x'
        run: |
          python -m pip install pyarrow

      - name: Install dependencies on win32
        if: matrix.envinfo.bdist-platform == 'win32' && (matrix.envinfo.python-version == '3.8.x' || matrix.envinfo.python-version == '3.9.x')
        run: |
          python -m pip install scipy==1.8.1
          python -m pip install pandas==1.2.5

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install -r requirements.txt

      - name: Run test case parallel
        id: test_case_parallel
        timeout-minutes: 90
        shell: bash
        run: |
          mkdir -p ${{ env.TESTLOGPATH }}
          pytest tqsdk/test --cov=./tqsdk --cov-report xml:coverage1.xml --show-capture=no -n auto -m "not nonparalleltest" --disable-warnings\
            --log-level=ERROR --log-file-format="%(asctime)s - %(levelname)s - %(module)s:%(filename)s:%(lineno)d - %(message)s" --log-file-date-format="%Y-%m-%d %H:%M:%S" \
            --log-file=${{ env.TESTLOGPATH }}${{ env.TESTLOGNAME }}.log

      - name: Run test case
        id: test_case_nonparallel
        timeout-minutes: 90
        shell: bash
        run: |
          pytest tqsdk/test --cov=./tqsdk --cov-report xml:coverage2.xml -m nonparalleltest --disable-warnings\
            --log-level=ERROR --log-file-format="%(asctime)s - %(levelname)s - %(module)s:%(filename)s:%(lineno)d - %(message)s" --log-file-date-format="%Y-%m-%d %H:%M:%S" \
            --log-file=${{ env.TESTLOGPATH }}${{ env.TESTLOGNAME }}.log

      - name: Upload log to artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TESTLOGNAME }}
          path: ${{ env.TESTLOGPATH }}