name: CI for tqsdk-python-private

on:
  repository_dispatch:
    types: [run-ci-*]
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  setup:
    name: log the workflow url in src repo in pr comment
    runs-on: ubuntu-latest

    env:
        PYTHONUNBUFFERED: 1
        PYTHONIOENCODING: "utf-8"
        PYTHONHASHSEED: 32
        TZ: ${{ matrix.envinfo.TZ }}
        TESTLOGPATH: "./log_archive/"
        TESTLOGNAME: ${{ matrix.envinfo.name }}

    steps:
    
    - name: Run test case parallel
      id: test_case_parallel
      timeout-minutes: 1
      shell: bash
      run: |
        exit 1

    - name: Run test case
      id: test_case_nonparallel
      if: ${{ always() }}
      timeout-minutes: 1
      shell: bash
      run: |
        exit 0
          
    - name: Print Test Result
      if: ${{ failure()  }}
      run: |
        echo ${{ steps.test_case_parallel.outcome != 'success' }}
        echo ${{ steps.test_case_nonparallel.outcome != 'success' }}
        echo ${{ github.event.client_payload.tag_flag != 'true' }}
        echo ${{ (steps.test_case_parallel.outcome != 'success' || steps.test_case_nonparallel.outcome != 'success') && github.event.client_payload.tag_flag != 'true' }}

    - name: Upload log to artifact
      if: ${{ failure() }}
      run:
        echo ${{ (steps.test_case_parallel.outcome != 'success' || steps.test_case_nonparallel.outcome != 'success') && github.event.client_payload.tag_flag != 'true' }}
